# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=75)),
                ('limit_exceed_chance', models.FloatField()),
                ('detected_spam_chance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_from', models.EmailField(max_length=75)),
                ('subject', models.CharField(max_length=150)),
                ('in_reply_to_header', models.CharField(max_length=150)),
                ('type', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
    ]
